telegram:
  bot:
   // username: Bextarinbot_bot
   // token: 8511492307:AAFwB_UMeYpwsFpduWVhBM_Sk8wUxSKjqnw

   username: Autosug_bot
  token: 8587484077:AAEkcmOZGsmsHbmYGUnWO-D7YzBbCUyxT70
  //admin-id: 973301293
  admin-id: 8059083289